In [3]:
import pandas as pd
data= pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [4]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train,test = train_test_split(data,test_size=0.2)

In [10]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1370,8.7,0.780,0.51,1.7,0.415,12.0,66.0,0.99623,3.00,1.17,9.2,5
1016,8.9,0.380,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.6,7
1120,7.9,0.540,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.1,8
174,7.3,0.380,0.21,2.0,0.080,7.0,35.0,0.99610,3.33,0.47,9.5,5
247,8.2,0.600,0.17,2.3,0.072,11.0,73.0,0.99630,3.20,0.45,9.3,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1376,8.2,0.885,0.20,1.4,0.086,7.0,31.0,0.99460,3.11,0.46,10.0,5
811,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6
337,7.8,0.430,0.32,2.8,0.080,29.0,58.0,0.99740,3.31,0.64,10.3,5
340,12.2,0.340,0.50,2.4,0.066,10.0,21.0,1.00000,3.12,1.18,9.2,6
1109,10.8,0.470,0.43,2.1,0.171,27.0,66.0,0.99820,3.17,0.76,10.8,6

In [11]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1381,6.8,0.830,0.09,1.8,0.074,4.0,25.0,0.99534,3.38,0.45,9.6,5
1533,8.0,0.390,0.30,1.9,0.074,32.0,84.0,0.99717,3.39,0.61,9.0,5
1244,5.9,0.290,0.25,13.4,0.067,72.0,160.0,0.99721,3.33,0.54,10.3,6
211,8.0,0.725,0.24,2.8,0.083,10.0,62.0,0.99685,3.35,0.56,10.0,6
590,9.0,0.450,0.49,2.6,0.084,21.0,75.0,0.99870,3.35,0.57,9.7,5
...,...,...,...,...,...,...,...,...,...,...,...,...
616,9.6,0.600,0.50,2.3,0.079,28.0,71.0,0.99970,3.50,0.57,9.7,5
743,11.6,0.410,0.58,2.8,0.096,25.0,101.0,1.00024,3.13,0.53,10.0,5
159,6.8,0.600,0.18,1.9,0.079,18.0,86.0,0.99680,3.59,0.57,9.3,6
1236,7.8,0.550,0.00,1.7,0.070,7.0,17.0,0.99659,3.26,0.64,9.4,6
1282,7.9,0.765,0.00,2.0,0.084,9.0,22.0,0.99619,3.33,0.68,10.9,6